netxlite: NewDefaultCertPoolWithExtraCerts constructor
ooni/probe-cli pull request #1129
Opened 2023-03-22 12:32 UTC by kelmenhorst

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/ooni/probe-cli/blob/master/CONTRIBUTING.md)
- [x] reference issue for this pull request: https://github.com/ooni/probe/issues/2444
- [ ] if you changed code inside an experiment, make sure you bump its version number

## Description
According to https://github.com/ooni/probe/issues/2444, this PR adds a new CA cert pool constructor `NewDefaultCertPoolWithExtraCerts` which returns a new default certificate pool with added certificates. This is done to encourage experiment code to only use a new certificate pool when it needs to add custom certificates to it.
`NewDefaultCertPool` is renamed to `NewMozillaCertPool`.

2023-04-03 11:41 UTC, bassosimone requested changes

2023-05-08 15:04 UTC, kelmenhorst commented on internal/netxlite/filtering/tls_test.go
> -				RootCAs:    netxlite.NewDefaultCertPool(),
Absolutely!

2023-05-08 15:05 UTC, kelmenhorst commented on internal/experiment/echcheck/handshake.go
> -
Agreed.

2023-05-30 14:15 UTC, bassosimone approved these changes
🐳

2023-05-30 14:27 UTC, merged