refactor: migrate database to internal
ooni/probe-cli pull request #979
Opened 2022-11-11 11:43 UTC by DecFox

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/ooni/probe-cli/blob/master/CONTRIBUTING.md)
- [x] reference issue for this pull request: https://github.com/ooni/probe/issues/2352
- [ ] if you changed anything related how experiments work and you need to reflect these changes in the ooni/spec repository, please link to the related ooni/spec pull request: 

## Description

This diff migrates the existing database implementation to `internal`.

2022-11-11 15:34 UTC, bassosimone requested changes
Thank you! I think we need to apply some changes before merging!

2022-11-11 15:34 UTC, bassosimone commented on internal/database/actions.go
> +	p, err := makeResultsDir(homePath, testGroupName, startTime)
If `utils.MakeResultsDir` is now unused, can you remove its implementation form the codebase?

2022-11-11 15:34 UTC, bassosimone commented on internal/database/actions.go
> +func CreateNetwork(sess db.Session, loc engine.LocationProvider) (*Network, error) {
Can you update the codebase to use `engine.LocationProvider` and delete `enginex.LocationProvider`?

2022-11-11 15:34 UTC, bassosimone commented on internal/database/utils.go
> +const ResultTimestamp = "2006-01-02T150405.999999999Z0700"
Perhaps this should be lowercase so it's not exported by `database`?

2022-11-11 16:05 UTC, DecFox commented on internal/database/actions.go
> +	if measurement.Measurement.MeasurementFilePath.Valid {
Yes! thank you for pointing this out

2022-11-11 16:05 UTC, DecFox commented
Thank you for the feedback! I have made the required changes.

2022-11-15 09:02 UTC, bassosimone approved these changes
:whale:

2022-11-15 09:02 UTC, bassosimone commented on internal/database/utils.go
> +// MakeResultsDir creates and returns a directory for the result
```suggestion
// makeResultsDir creates and returns a directory for the result
```

2022-11-15 09:33 UTC, bassosimone commented
I have checked how the CI is failing and 🤷... I will merge because the failures seem unrelated and transient network issues. If I am wrong, this kind of failure will continue throughout the day, eventually forcing me to look deeper into it.

2022-11-15 09:35 UTC, merged